version: "3.9"
services:
  # Base image for services
  base:
    image: base-runtime
    build:
      context: .
      dockerfile: ./docker/base/Dockerfile
    command: echo
  database:
    image: postgres
    container_name: db-instance
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

  # Shopping cart entry
  entry:
    container_name: entry
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_CODEBASE: ./src/services
        MODULE: entry
    ports:
      - "8000:8000"

  # REST API
  user:
    container_name: user
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_CODEBASE: ./src/services
        MODULE: user
    ports:
      - "8001:8000"
    depends_on:
      - database
  product:
    container_name: product
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_CODEBASE: ./src/services
        MODULE: product
    ports:
      - "8002:8000"
    depends_on:
      - database
  cart:
    container_name: cart
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_CODEBASE: ./src/services
        MODULE: cart
    ports:
      - "8003:8000"
    depends_on:
      - database
  cart_detail:
    container_name: cart_detail
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_CODEBASE: ./src/services
        MODULE: cart_detail
    ports:
      - "8004:8000"
    depends_on:
      - database
  order:
    container_name: order
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_CODEBASE: ./src/services
        MODULE: order
    ports:
      - "8005:8000"
    depends_on:
      - database
